### ISSUE TITLE
Unable to Run 3D Example Successfully

### ISSUE THREAD

**Issue by yuhangchill** [dbukenberger/InfinityVoronoi#1]
Hi, I was trying to generate a 3D Voronoi diagram using the Manhattan L1 or Chebyshev metric, I followed the instructions in the README to run runExamples3D.py to generate a 3D Voronoi diagram, but encountered some error during execution.

***Situation***: 
Failed after Dissolving step reaching 11%. 3/27
```
Traceback (most recent call last):
  File "lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "ChebyshevObject.py", line 105, in dissolveMP
    dCell.dissolve()
  File "DissCell.py", line 25, in dissolve
    self.dissolveFaces()
  File "DissCell.py", line 102, in dissolveFaces
    merged = self.mergeFaces(fIdx, fJdx)
  File "DissCell.py", line 75, in mergeFaces
    newFace = edgesToPath(edges)
  File "lib\site-packages\drbutil\util.py", line 85, in edgesToPath
    path = edges.pop(0)
IndexError: pop from empty list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runExamples3D.py", line 16, in <module>
    cObj.computeDiagram()
  File "ChebyshevObject.py", line 357, in computeDiagram
    fun()
  File "ChebyshevObject.py", line 328, in dissolveCells
    self.processDissolvedSectors(self.map(dissolveMP, self.cellSectors, 'dissolving'))
  File "ChebyshevObject.py", line 223, in map
    return list(tqdm(mapIterator, total=len(iterData), ascii=True, desc=desc + self.mpDesc))
  File "lib\multiprocessing\pool.py", line 868, in next
    raise value
IndexError: pop from empty list
```

***Attempted Fix***:
I tried to only use single CPU core at the beginning and doesn't work
I tried adding the following condition in DissCell.py to prevent an empty edge list error:
```
if len(edges) == 0:
    return False
```
I also added import warnings at the start of ChebyshevObject3D.py, 
```
import warnings
```
these allowed the script to run, but the generated Voronoi diagram still does not appear correct.

Could you please help investigate this issue?

**Comment by dbukenberger** [comment]
Hey,
thanks for pointing that out - in what configuration are you running into this error?
When I start the script, I am not able to reproduce it. (Python 3.8 and NumPy 1.24.4)

**Comment by yuhangchill** [comment]
Thank you so much for responding. Mine env in anaconda: Python 3.8.19, Numpy 1.24.4

**Comment by dbukenberger** [comment]
Hey, I've tracked down the issue to a recent change in `edgesToPath()` in the `drbutil` lib - and fixed it there.
If you have installed the lib, update it with pip - or if imported from source, delete the `drbutil` folder and rerun the script.
In my tests, this fixed the issue - but let me know if it also works for you now.

**Comment by yuhangchill** [comment]
Amazing! After updating the library, I was able to successfully run and view the beautiful demo3D_axisAligned.obj model. The few remaining minor issues are likely caused by my own environment. Thank you once again for your incredible work, and I apologize for the feedback delays due to the time difference.

**Comment by dbukenberger** [comment]
Great, thanks for your feedback.
